### ISSUE TITLE
Create Input styles

### ISSUE THREAD

**Issue by RIP21** [itacademypl/portal-frontend#4]
![image](https://user-images.githubusercontent.com/3940079/39896380-8670071c-54b6-11e8-8ff7-33d92678c62f.png)

- Styles

**Comment by iskrypnyk** [comment]
What are the flags that input is correct?

**Comment by RIP21** [comment]
@iskrypnyk just prepare the CSS :) Forget about the JS part if it's what you mean by flags :)
